title:  Калина Алексей
tagline:  блог программиста

disqus:
  comments: false
  disqus_shortname: 'alexeykalina'

google-ID: ''

menu:
- {name: 'Обо мне', url: 'about.html'}
- {name: 'Архив', url: 'writing.html'}
- {name: 'Контакты', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/AlexeyKalina'}
- {icon: 'envelope', link: 'mailto:alexey.kalina96@gmail.com'}
- {icon: 'rss-square', link: 'rss-feed.xml'}
